### ISSUE TITLE
SubModel技能在mm5.1.4无法正常工作 

### ISSUE THREAD

**Issue by Shimatzukaze** [GceCold/OrangeMechanic#1]
SubModel技能在mm5.1.4无法正常工作，已经另行测试同配置meg执行正常。
报错信息:
[22:31:12] [lumine-scheduler-67/ERROR]: [MythicMobs] [31m[SCHEDULER] Exception thrown whilst executing task[37m
[22:31:12] [lumine-scheduler-67/WARN]: java.lang.NullPointerException: Cannot invoke "io.lumine.mythic.api.skills.placeholders.PlaceholderString.get(io.lumine.mythic.core.skills.placeholders.PlaceholderMeta, io.lumine.mythic.api.adapters.AbstractEntity)" because "this.partId" is null
[22:31:12] [lumine-scheduler-67/WARN]: 	at OrangeMechanic-1.0.5-SNAPSHOT.jar//ltd.icecold.orangeengine.mythicmobs.v5.mechanics.MechanicSubModel.castAtEntity(MechanicSubModel.java:40)
[22:31:12] [lumine-scheduler-67/WARN]: 	at MythicMobs-5.1.4 premium.jar//io.lumine.mythic.core.skills.SkillMechanic.lambda$executeTargetedEntitySkill$7(SkillMechanic.java:520)
[22:31:12] [lumine-scheduler-67/WARN]: 	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[22:31:12] [lumine-scheduler-67/WARN]: 	at MythicMobs-5.1.4 premium.jar//io.lumine.mythic.core.skills.SkillMechanic.executeTargetedEntitySkill(SkillMechanic.java:516)
[22:31:12] [lumine-scheduler-67/WARN]: 	at MythicMobs-5.1.4 premium.jar//io.lumine.mythic.core.skills.SkillMechanic.lambda$executeSkills$3(SkillMechanic.java:473)
[22:31:12] [lumine-scheduler-67/WARN]: 	at MythicMobs-5.1.4 premium.jar//io.lumine.mythic.core.skills.SkillMechanic.runMechanic(SkillMechanic.java:511)
[22:31:12] [lumine-scheduler-67/WARN]: 	at MythicMobs-5.1.4 premium.jar//io.lumine.mythic.core.skills.SkillMechanic.executeSkills(SkillMechanic.java:473)
[22:31:12] [lumine-scheduler-67/WARN]: 	at MythicMobs-5.1.4 premium.jar//io.lumine.mythic.core.skills.SkillMechanic.execute(SkillMechanic.java:390)
[22:31:12] [lumine-scheduler-67/WARN]: 	at MythicMobs-5.1.4 premium.jar//io.lumine.mythic.core.mobs.MobType.lambda$executeSkills$4(MobType.java:1140)
[22:31:12] [lumine-scheduler-67/WARN]: 	at MythicMobs-5.1.4 premium.jar//io.lumine.mythic.bukkit.utils.Delegates$RunnableToSupplier.get(Delegates.java:121)
[22:31:12] [lumine-scheduler-67/WARN]: 	at MythicMobs-5.1.4 premium.jar//io.lumine.mythic.bukkit.utils.promise.LuminePromise$SupplyRunnable.run(LuminePromise.java:654)
[22:31:12] [lumine-scheduler-67/WARN]: 	at MythicMobs-5.1.4 premium.jar//io.lumine.mythic.bukkit.utils.tasks.LumineExecutors$SchedulerWrappedRunnable.run(LumineExecutors.java:70)
[22:31:12] [lumine-scheduler-67/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[22:31:12] [lumine-scheduler-67/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[22:31:12] [lumine-scheduler-67/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by GceCold** [comment]
请在技能文件中添加partId配置项
